### ISSUE TITLE
Held Actions/Ambushes/Surprise Rounds

### ISSUE THREAD

**Issue by LockerM** [DeckofAdventures/TheGame#110]
### Scenario - Ambush 

Three characters wait around a corner for another to lure the enemy right to them. When that combat is initiated, they would all draw Target Cards and go on that order. 

### Question

How do we create and word the rules for Ambushes or Surprise Rounds where the characters each 'hold' one Major Action that goes off before the top of the first round? And what happens if the 'held' action criteria isn't met (I see an enemy) after 6 seconds, in the event the ambush/lure doesn't go off as planned? Do multiple rounds of combat happen outside of their turn order while they wait, or do they draw TCs to begin combat anyway and then act when the 'trigger' happens still?

**Comment by D-D-2** [comment]
I've never forced a player to lose their action/turn if they held their action for a specific trigger but that trigger doesn't happen. Holding an action typically has some punishments already - loss of secondary action, loss of movement if not already used. 

Surprise Round: On a successful ambush, all of the ambushers draw their TC and may each take their turn. After this round, those being ambushed will draw their TC and be added to the turn order in their respective slot. 

Holding an action: In a round in initiative order, you may choose to hold your action with a stated trigger. At the end of the round, if the trigger did not occur, you may then take your action. While holding your action, you cannot move or take minor actions, and you cannot benefit from or utilize your passive abilities. (last part may be a bit harsh.)

**Comment by LockerM** [comment]
I really like that proposal for Surprise Round @D-D-2 - that feels really clean to me and makes sense to have an entire round still be in turn order but wait to slot the 'ambushed' party in until after the first round. This will apply on the GM side as well when the enemies get the drop on the players. 

Held Actions and Held Turns still feel like something we'll want to flesh out some more and make a decision on. 

@CBroz1 we originally put the idea of holding an entire turn until later in the initiative order, would we want to keep that in here and make that the only way to 'hold' something? Or would players be able to 'hold' an action for a trigger - without Reactions as an explicit mechanic the 'holding' of an action feels like something that gets into that territory, so I'm wary of how we want to solve for that one specifically.

**Comment by CBroz1** [comment]
My previous proposal regarding held turns was to promote collaboration. We removed the mechanic that rewarded 'simultaneous' turns. 

Yes, holding pending trigger can substitute for reactions

I'd be concerned about end of the round 'if the trigger didn't occur' circumstances. They they just do what anyway? The same thing they'd planned? Some actions might be contingent other things happening - do they get to change what they were gonna do? If no penalty, I think we'd see a lot of players 'holding' because circumstances might improve and then a lot of GM frustration figuring out which held action goes when. Like an embedded round baked into the end of the real round

**Comment by LockerM** [comment]
I feel like holding turns makes sense to keep as we have players who are not sure what to do yet, want to go after the Defender goes to set up a combo even though they drew a higher TC, etc. 

I propose keeping "You can choose to hold your turn until the end of another creature's turn. If you do not act before the end of the round, your turn is forfeited." 

Additionally within that, holding an action feels specific to a stated trigger. I am using my Major Action on my turn to 'hold' a Power or Action for a stated trigger. When that trigger occurs (i.e. an enemy enters my range within 1 space) I will use my Major Action. If the trigger does not occur, your Major Action is 'spent' and cannot be changed. 

*Remaining question of harshness on the above ruling - if a held action is a Power required PP does the character still lose that PP?*

**Comment by CBroz1** [comment]
I think, yes, the PP is also spent. It takes the resource to attempt something. The wording of `Attack, Charge` reflects that design

**Comment by D-D-2** [comment]
Not sure if I agree about held actions as a substitute for a reaction. Held actions are anticipating something in advance, whereas a reaction is only able to be done after someone does something else. I think of it as a reflex. My character can prepare/anticipate anything, but has specific training ingrained in them for "When X happens, do Y." I think both can exist. 

Regarding holding entire turns, there are certain times I've allowed players to do this (even when stated it's not allowed in the rules) because it was narratively relevant and made for a more impactful moment. I could see something where players could agree to trade turn order at the beginning of initiative, but not in the middle of a combat.

**Comment by CBroz1** [comment]
Sure, reaction and held action are not synonymous. I guess by 'substitute', I meant play a similar role to reactions when we've so far elected not to include them

**Comment by D-D-2** [comment]
@LockerM @CBroz1 
The wording of surprise indicates that those being surprised cannot use a reaction (if we put reactions in the game). I'm fine with this as long as you both are too.

**Comment by CBroz1** [comment]
ya - we can revisit if and when we add reactions
