### ISSUE TITLE
Contested Checks versus Saving Checks "Saves"

### ISSUE THREAD

**Issue by LockerM** [DeckofAdventures/TheGame#111]
## Contested Checks are confusing and need to be cleared up. 

We need to clarify between when a Check is truly Contested (i.e. Tackle) or when someone is making a Saving Check - *Save* - and drawing against their own Target Card. This needs to be explicit in the core ruleset, and then also made clear on Powers as needed.
## Contested Checks vs. Saving Checks

When do the following happen, and how can we write this into the rules to be extremely clear:
1. Contested Check: The initiator draws a Card. This is the Target Card for the Target to aim their Check against. 
- (*Or does the Target simply draw a card against the initiator's TC?)*
3. Saving Check: The initiator spends a resource (FP, a Major Action, etc.) to force target to make a Save. That target draws a Saving Check against their own TC. 

## Alt proposed names for the mechanic (open to others, too)

1. *Save* and *Contest*
2. *Saving Draw* and *Contested Draw*
3. *Saving Check* and *Contested Check*

**Comment by D-D-2** [comment]
- What is the rationale for making the check against their own TC rather than against the initiators TC? 
- The entangle power requires the initiator to use a P.P., and the target is required to save. To me, it makes sense to draw against the TC of the entangler rather than against myself. 
- Contested checks is will vs. will, while a save is trying to make it so the initiators goal doesn't happen. However, sometimes an "ability check" can fall under that definition as well, at least in other TTRPG systems.
- Is it also possible that a contested check could be something where both the initiator and the target are drawing a card against a TC the GM draws and the closest to this TC wins the check. I can see this being fun and possible for GMs to dramatize, like waiting on the river card in poker with your hand shown.

**Comment by LockerM** [comment]
Is a "Save" just a Contested Check against my own TC? 

Keep it where the initiator's primary skill mod reduces down from a DR 3 to `DR 3-(N/2)`

We should put some Powers together to make sure to include or emphasize that the person making a Save has the DR set by the caster's stats

**Comment by LockerM** [comment]
Can we add different types of Epic Events that can include DD2's 4th bullet above?

From @D-D-2 - Suited hit against a TC, within a range, same card of the same suit (critical), or just direct comparison of cards to see which one is closer wins?

**Comment by LockerM** [comment]
Language Clarification: 

Draws 
- Saves
- Checks
     - Contested Checks
