### ISSUE TITLE
Website minor fixes

### ISSUE THREAD

**Issue by CBroz1** [DeckofAdventures/TheGame#126]
@LockerM @D-D-2 Please Explore [the new site](https://deckofadventures.github.io/TheGame/) and let me know what bugs you find

Typos, bugs:
- [x] Add linebreak between armor table title and table 
- [x] embedded section links on guide full don't go to section - try lowercase
- [x] embedded lists
   - [x] guide full fate cards items '5. 6' 
   - [x] guide full starting adventure 'if link expired'
- [x] gm guide 
   - [x] skills breakdown - full player's guide - apostrophe
   - [x]  contested checks and epic events - player guide - singular -> possessive
- [x] add semicolons to all glossary items.
- [x] Changelog, contrib, code 404 on docker only

Significant fixes
- [x] limit toc rendering to 3 levels
- [ ] Powers list doesn't render #121 
- [ ] add license to global nav

**Comment by LockerM** [comment]
- [ ] Glossary shows AC not AR

**Comment by LockerM** [comment]
Google Analytics tracking doesn't seem to be firing. Here are the full instructions from their site - I believe it needs to render in the code on every page (is this part of our could it be part of the compiling action of the build process rather than hand-coded in each .md file? not sure on the process there) 

> **Install the Google tag manually**
>Below is the Google tag for this account. Copy and paste it in the code of every page of your website, immediately after the <head> element. Don’t add more than one Google tag to each page.

`
<script async src="https://www.googletagmanager.com/gtag/js?id=G-NVDBHE89HX"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-NVDBHE89HX');
</script>`

**Comment by CBroz1** [comment]
[Analytics Documentation](https://squidfunk.github.io/mkdocs-material/setup/setting-up-site-analytics/)

**Comment by CBroz1** [comment]
How important is case-insensitivity? Looks like it would be a [tough solve](https://stackoverflow.com/questions/48388057/how-to-make-github-pages-url-case-insensitive#:~:text=The%20short%20answer%20is%3A%20You,most%20webservers%20will%20respect%20that.)
