### ISSUE TITLE
Nerf the Support Class

### ISSUE THREAD

**Issue by D-D-2** [DeckofAdventures/TheGame#163]
## Healing
Currently, the support class can heal up to 3 HP at level 2. This is anywhere from 38% to 50% of HP Max depending on the character. At a low level, I do not think the support class should be able to heal this much. I propose major heal being locked behind a higher level, perhaps as high as 5. Fate Cards being able to nullify a point of damage also makes the major heal all the more difficult to beat. 

## Lend Vigor 
Lend Vigor currently allows up to 2 additional major actions, and 4 additional spaces of movement. That effect is so powerful it could be separated into two different abilities, and both abilities would still be excellent utility (however the major actions would be inherently better). I propose lend vigor to be at least 2 PP, and only target one character until level 4 or higher. 

### Anecdote
After running my first game, I found myself stunned by the support class multiple times in combat. I threw 7 enemies at one character after they already went through a combat, and it wasn't a sufficient amount of pressure to down them after they made a risky play.

**Comment by LockerM** [comment]
**Ideas for resolution:**

I like the idea of tweaking Supports Powers to be more stamina draining and require for some Powers the proximity of a “hit” on a heal being what determines its power. See below for proposed changes to Heal and Lend Vigor. 

**Proposed change to Minor Heal**

Minor Heal: 2PP, heals 1 HP. Maybe minor heal always works for 1 hp no matter what but you perform a Craft Check DR 3, on a success it heals an additional 1 hp for the same PP. A major success would then heal 3 HP, so "minor heal” always costs 2pp and it varies from 1 HP to 3 HP healed based on the check’s success. That way it burns at least 1 card and 2 PP making it a fairly resource intensive cast with variable result. This can scale over time with "Major Heal" unlocking maybe at level 4 or 5, defaulting to 2 or even 3 HP healed with an extra 1-2 Hp healed depending on a hit. 


**Proposed Change to Lend Vigor**

Lend vigor it might be just making it 2PP for one use on one target and removing the ability to double cast it, at least until higher levels. Then Supports might have some really strong abilities but they’re balancing the use of PP much more than other characters.

Since Lend Vigor only affects a single character and a single turn, it's definitely still powerful but will be fairly balanced across the rest of the support's kit and comparatively to the other Roles' Powers feels more in balance. 

"Mass Lend Vigor" can unlock at level 4 or 5 and allow for a double cast maybe for 3PP, or allow just the major action for up to 3 targets but no move speed for example.

**Comment by CBroz1** [comment]
Addressed in #174
