### ISSUE TITLE
Does `DR + Mod on report` make sense?

### ISSUE THREAD

**Issue by CBroz1** [DeckofAdventures/TheGame#59]
vs. `DR = base DR + Mod`? 
- It's easier for the GM to report the DR, and no confusion about DR being the same for all. 
- It's easier for player to think of a wider DR

**Comment by LockerM** [comment]
Players prefer to know their unique DR to avoid "2 + 2 = 4" when drawing a card. Playtesters reported confusion of target card success and relied on the GM after a playtest because of the mod. 

Recommended to test or revert to - "Base DR Vs. modified DR" where Modified DR is the players mod + DR - this allows for the +1 +2 to make more sense as well, as the player you add your modifier to the DR to determine your range of success on the draw.
