### ISSUE TITLE
Mystic Recovery - additional costs

### ISSUE THREAD

**Issue by CBroz1** [DeckofAdventures/TheGame#76]
Out of combat, this could yield 3FP for free. Instead, it could be a supplemental 'burn mechanic'

**Comment by LockerM** [comment]
Looking to resolve as part of #63

**Comment by LockerM** [comment]
Interim fix: As a power - this needs to be removed

**Comment by D-D-2** [comment]
Also something to keep in mind, if we go with some of those first draft necromancer powers later on, every ability to get cards into the discard pile goes from being a cost, to a benefit. While I think it is worth it to incorporate the discard pile as a mechanic rather than a dump site, it does have the ability to bust the meta of the game.

**Comment by LockerM** [comment]
Thanks @D-D-2! Good to know it was something that felt OP when it was on the character sheet. 

I think there's opportunities for us to allow for PP recovery between rests for Casters as a Passive or even with Magic Items, but as it stands we can remove the existing Power from the list.

**Comment by LockerM** [comment]
Removed power in PR #117.
